name: "Test"
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["4", "4.3.2", "6", "8", "10", "lts/*", "node"]
    steps:
    - uses: actions/checkout@v1.0.0
    - uses: dcodeIO/setup-node-nvm@v1.0.0
      with:
        node-version: ${{ matrix.node_version }}
    - name: "Install dependencies"
      run: npm ci --no-audit
    - name: "Run tests"
      run: npm test
  bench:
    name: "Bench"
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v1.0.0
    - uses: dcodeIO/setup-node-nvm@v1.0.0
      with:
        node-version: "lts/*"
    - name: "Install dependencies"
      run: npm ci --no-audit
    - name: "Run benchmark"
      run: npm run bench
